from __future__ import annotations
from pathlib import Path


def apply(root: Path) -> None:
    _patch_server(root / 'server.py')
    _patch_db(root / 'db.py')
    _patch_index(root / 'static' / 'index.html')
    _patch_appjs(root / 'static' / 'app.js')
    sw=root/'static'/'sw.js'
    if sw.exists():
        text=sw.read_text(encoding='utf-8').replace("jj-arena-live-v3","jj-arena-live-v5")
        sw.write_text(text,encoding='utf-8')


def _patch_server(p: Path) -> None:
    s=p.read_text(encoding='utf-8')
    s=s.replace('import time\n','import time\nimport hashlib\nimport unicodedata\n')
    s=s.replace('    if not int(user.get("approved") or 0):\n        raise HTTPException(403, "approval pending")\n','')
    a=s.index('def _login_key('); b=s.index('\n\nclass PointEntry',a)
    block='''def normalize_login_name(value: str) -> str:\n    name = unicodedata.normalize("NFKC", value or "").strip().replace(" ", "").replace("\\u3000", "")\n    chars=[]\n    for ch in name:\n        code=ord(ch)\n        if 0x3041 <= code <= 0x3096:\n            ch=chr(code+0x60)\n        chars.append(ch)\n    name="".join(chars)\n    if not re.fullmatch(r"[ァ-ヺー・]{2,20}", name):\n        raise HTTPException(400, "名前はカタカナ2〜20文字で入力してください")\n    return name\n\n\ndef internal_login_id(name: str) -> str:\n    digest=hashlib.sha256(name.encode("utf-8")).hexdigest()[:32]\n    return f"pin-{digest}@jj.invalid"\n\n\ndef validate_pin(pin: str) -> str:\n    pin=str(pin or "").strip()\n    if not re.fullmatch(r"\\d{6}", pin):\n        raise HTTPException(400, "暗証番号は6桁の数字で入力してください")\n    return pin\n\n\ndef _login_key(request: Request, identity: str) -> str:\n    host = request.client.host if request.client else "unknown"\n    digest = hashlib.sha256(identity.encode()).hexdigest()\n    return f"{host}:{digest}"\n\n\ndef _check_login_rate(request: Request, identity: str) -> str:\n    key=_login_key(request,identity); now=time.time(); recent=[t for t in _LOGIN_ATTEMPTS.get(key,[]) if now-t<600]\n    _LOGIN_ATTEMPTS[key]=recent\n    if len(recent)>=5:\n        raise HTTPException(429,"暗証番号の試行が多すぎます。10分ほど時間をおいてください")\n    return key\n\ndef _record_login_failure(key: str) -> None:\n    _LOGIN_ATTEMPTS.setdefault(key,[]).append(time.time())\n\n\nclass PinAccess(BaseModel):\n    name: str = Field(min_length=1, max_length=30)\n    pin: str = Field(min_length=6, max_length=6)\n\n\nclass ChangePinIn(BaseModel):\n    current_pin: str = Field(min_length=6, max_length=6)\n    new_pin: str = Field(min_length=6, max_length=6)\n\n\nclass ResetPinIn(BaseModel):\n    pin: str = Field(min_length=6, max_length=6)\n'''
    s=s[:a]+block+s[b:]
    s=s.replace('''class ChangePasswordIn(BaseModel):\n    current_password: str\n    new_password: str = Field(min_length=8, max_length=200)\n\n\n''','')
    s=s.replace('    approved: bool | None = None\n','')
    s=s.replace('    disabled: bool | None = None\n    disabled: bool | None = None\n','    disabled: bool | None = None\n')
    s=s.replace('''class AdminReauthIn(BaseModel):\n    password: str = Field(min_length=1, max_length=200)\n\n\n''','')
    for old in ('1.4.0','1.4.1','1.4.2'):
        s=s.replace(f'version="{old}"','version="1.5.0"').replace(f'"version":"{old}"','"version":"1.5.0"')
    a=s.index('@app.post("/api/auth/signup")'); b=s.index('@app.post("/api/auth/logout")',a)
    auth='''@app.post("/api/auth/pin")\ndef pin_access(payload: PinAccess, response: Response, request: Request):\n    name=normalize_login_name(payload.name)\n    pin=validate_pin(payload.pin)\n    login_id=internal_login_id(name)\n    key=_check_login_rate(request,login_id)\n    created=False\n    with db.connect() as con:\n        row=con.execute("SELECT * FROM users WHERE email=?",(login_id,)).fetchone()\n        if not row:\n            try:\n                uid=db.insert_returning_id(con,\n                    "INSERT INTO users(name,email,password_hash,role,arena_chips,xp,approved,disabled,ranking_name,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)",\n                    (name,login_id,db.hash_password(pin),"member",0,0,1,0,name,db.utcnow()),\n                )\n                row=con.execute("SELECT * FROM users WHERE id=?",(uid,)).fetchone()\n                created=True\n            except Exception:\n                row=con.execute("SELECT * FROM users WHERE email=?",(login_id,)).fetchone()\n        if not row or not db.verify_password(pin,row["password_hash"]):\n            _record_login_failure(key)\n            raise HTTPException(401,"名前または暗証番号が違います")\n        rowd=dict(row)\n        if int(rowd.get("disabled") or 0):\n            raise HTTPException(403,"このアカウントは利用停止中です")\n        if db.password_needs_rehash(rowd["password_hash"]):\n            con.execute("UPDATE users SET password_hash=? WHERE id=?",(db.hash_password(pin),rowd["id"]))\n    _LOGIN_ATTEMPTS.pop(key,None)\n    token=db.create_session(rowd["id"]); set_session_cookie(response,token)\n    return {"user":user_payload(rowd["id"]),"created":created}\n\n\n@app.post("/api/auth/signup")\ndef legacy_signup_disabled():\n    raise HTTPException(410,"メール登録は廃止しました。名前と6桁PINを利用してください")\n\n\n@app.post("/api/auth/login")\ndef legacy_login_disabled():\n    raise HTTPException(410,"メールログインは廃止しました。名前と6桁PINを利用してください")\n\n\n'''
    s=s[:a]+auth+s[b:]
    a=s.index('@app.post("/api/auth/change-password")'); b=s.index('\n\ndef user_payload',a)
    change='''@app.post("/api/auth/change-pin")\ndef change_pin(payload: ChangePinIn, request: Request, user=Depends(current_user)):\n    current_pin=validate_pin(payload.current_pin); new_pin=validate_pin(payload.new_pin)\n    if current_pin==new_pin:\n        raise HTTPException(400,"現在と異なる暗証番号を設定してください")\n    with db.connect() as con:\n        row=con.execute("SELECT password_hash FROM users WHERE id=?",(user["id"],)).fetchone()\n        if not row or not db.verify_password(current_pin,row["password_hash"]):\n            raise HTTPException(400,"現在の暗証番号が違います")\n        con.execute("UPDATE users SET password_hash=? WHERE id=?",(db.hash_password(new_pin),user["id"]))\n    db.delete_user_sessions(user["id"],keep_token=request_token(request))\n    return {"ok":True}\n'''
    s=s[:a]+change+s[b:]
    s=s.replace('SELECT id,name,email,role,xp,approved,disabled,ranking_name,created_at FROM users WHERE id=?','SELECT id,name,role,xp,disabled,ranking_name,created_at FROM users WHERE id=?')
    a=s.index('def _mask_email('); b=s.index('@app.patch("/api/admin/members/{user_id}")',a)
    admin='''@app.get("/api/admin/members")\ndef list_members(user=Depends(admin_user)):\n    with db.connect() as con:\n        rows=con.execute("SELECT id,name,role,disabled,ranking_name,created_at FROM users ORDER BY disabled ASC,name ASC").fetchall()\n    return [dict(row) for row in rows]\n\n\n@app.post("/api/admin/members/{user_id}/reset-pin")\ndef reset_member_pin(user_id:int,payload:ResetPinIn,user=Depends(admin_user)):\n    pin=validate_pin(payload.pin)\n    with db.connect() as con:\n        row=con.execute("SELECT id FROM users WHERE id=?",(user_id,)).fetchone()\n        if not row:\n            raise HTTPException(404,"member not found")\n        con.execute("UPDATE users SET password_hash=? WHERE id=?",(db.hash_password(pin),user_id))\n    db.delete_user_sessions(user_id)\n    return {"ok":True}\n\n\n'''
    s=s[:a]+admin+s[b:]
    s=s.replace('''        if payload.approved is not None:\n            con.execute("UPDATE users SET approved=? WHERE id=?",(1 if payload.approved else 0,user_id))\n''','')
    s=s.replace('    should_eject = payload.disabled is True or payload.approved is False\n','    should_eject = payload.disabled is True\n')
    s=s.replace('    if int(user.get("disabled") or 0) or not int(user.get("approved") or 0):\n        await ws.close(code=4403)\n        return\n','    if int(user.get("disabled") or 0):\n        await ws.close(code=4403)\n        return\n')
    p.write_text(s,encoding='utf-8')


def _patch_db(p: Path) -> None:
    s=p.read_text(encoding='utf-8')
    legacy = '        if \"chips\" in cols: con.execute(\"UPDATE users SET arena_chips=chips WHERE arena_chips=0\")\n'
    fixed = '''        if \"chips\" in cols:\n            con.execute(\"UPDATE users SET arena_chips=COALESCE(NULLIF(arena_chips,0),chips,0) WHERE arena_chips IS NULL OR arena_chips=0\")\n        else:\n            con.execute(\"UPDATE users SET arena_chips=0 WHERE arena_chips IS NULL\")\n        if \"xp\" in cols:\n            con.execute(\"UPDATE users SET xp=0 WHERE xp IS NULL\")\n        if \"role\" in cols:\n            con.execute(\"UPDATE users SET role='member' WHERE role IS NULL OR role='' \")\n        con.execute(\"ALTER TABLE users ALTER COLUMN arena_chips SET DEFAULT 0\")\n        con.execute(\"ALTER TABLE users ALTER COLUMN arena_chips SET NOT NULL\")\n        if \"xp\" in cols:\n            con.execute(\"ALTER TABLE users ALTER COLUMN xp SET DEFAULT 0\")\n            con.execute(\"ALTER TABLE users ALTER COLUMN xp SET NOT NULL\")\n'''
    if legacy in s:
        s=s.replace(legacy,fixed)
    s=s.replace('ONLINE_POINTS_PER_BB = 3.0','ONLINE_POINTS_PER_BB = 3')
    marker='''def password_needs_rehash(encoded: str | None) -> bool:\n    if not encoded or not encoded.startswith("pbkdf2_sha256$"):\n        return True\n    try:\n        _, rounds, _, _ = encoded.split("$", 3)\n        return int(rounds) < 600_000\n    except Exception:\n        return True\n\n\n'''
    if marker in s:
        replacement='''PBKDF2_ROUNDS = int(os.getenv("JJ_PBKDF2_ROUNDS", "600000"))\n\ndef password_needs_rehash(encoded: str | None) -> bool:\n    if not encoded or not encoded.startswith("pbkdf2_sha256$"):\n        return True\n    try:\n        _, rounds, _, _ = encoded.split("$", 3)\n        return int(rounds) < PBKDF2_ROUNDS\n    except Exception:\n        return True\n\n\ndef internal_login_id(name: str) -> str:\n    digest=hashlib.sha256(name.encode("utf-8")).hexdigest()[:32]\n    return f"pin-{digest}@jj.invalid"\n\n\ndef _scrub_legacy_emails(con) -> None:\n    rows=con.execute("SELECT id,email FROM users").fetchall()\n    for row in rows:\n        rd=dict(row); email=str(rd.get("email") or "")\n        if email.endswith("@jj.invalid"):\n            continue\n        con.execute("UPDATE users SET email=? WHERE id=?",(f"legacy-{int(rd['id'])}@jj.invalid",rd["id"]))\n\n\ndef _ensure_pin_admin(con) -> None:\n    name=os.getenv("JJ_ADMIN_NAME","ケンイチロウ").strip() or "ケンイチロウ"\n    pin=(os.getenv("JJ_ADMIN_PIN") or "").strip()\n    if not (len(pin)==6 and pin.isdigit()):\n        return\n    login_id=internal_login_id(name)\n    row=con.execute("SELECT id FROM users WHERE email=?",(login_id,)).fetchone()\n    if not row:\n        uid=insert_returning_id(con,"INSERT INTO users(name,email,password_hash,role,arena_chips,xp,approved,disabled,ranking_name,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)",(name,login_id,hash_password(pin),"admin",0,0,1,0,name,utcnow()))\n    else:\n        uid=int(row["id"]); con.execute("UPDATE users SET role='admin',approved=1,disabled=0,name=? WHERE id=?",(name,uid))\n    old=con.execute("SELECT id FROM users WHERE role='admin' AND id<>?",(uid,)).fetchall()\n    for other in old:\n        con.execute("UPDATE users SET role='member' WHERE id=?",(other["id"],))\n        con.execute("DELETE FROM sessions WHERE user_id=?",(other["id"],))\n\n\n'''
        s=s.replace(marker,replacement)
    s=s.replace('    rounds = 600_000\n','    rounds = int(os.getenv("JJ_PBKDF2_ROUNDS", "600000"))\n')
    s=s.replace('con.execute("UPDATE online_hand_results SET points=ROUND(result_bb * ?, 2)", (ONLINE_POINTS_PER_BB,))','con.execute("UPDATE online_hand_results SET points=result_bb * ?", (ONLINE_POINTS_PER_BB,))')
    s=s.replace('''    with connect() as con:\n        _migrate_legacy_beta(con); con.executescript(schema); _ensure_access_columns(con); _ensure_online_hand_columns(con)\n''','''    with connect() as con:\n        _migrate_legacy_beta(con); con.executescript(schema); _ensure_access_columns(con); _ensure_online_hand_columns(con)\n        _scrub_legacy_emails(con)\n        _ensure_pin_admin(con)\n''')
    old='''        if con.execute("SELECT COUNT(*) c FROM users").fetchone()["c"] == 0:\n            admin_name=os.getenv("JJ_ADMIN_NAME","ケンイチロウ"); admin_email=os.getenv("JJ_ADMIN_EMAIL","admin@jj.local"); admin_password=os.getenv("JJ_ADMIN_PASSWORD") or "admin2026"\n            con.execute("INSERT INTO users(name,email,password_hash,role,arena_chips,xp,approved,disabled,ranking_name,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)",(admin_name,admin_email,hash_password(admin_password),"admin",0,0,1,0,admin_name,utcnow()))\n            if os.getenv("JJ_ENABLE_DEMO_MEMBER", "1" if not IS_POSTGRES else "0") == "1":\n                con.execute("INSERT INTO users(name,email,password_hash,role,arena_chips,xp,approved,disabled,ranking_name,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)",("ヨシハル","member@jj.local",hash_password("jj2026"),"member",0,0,1,0,"ヨシハル",utcnow()))\n'''
    s=s.replace(old,'        _ensure_pin_admin(con)\n')
    p.write_text(s,encoding='utf-8')


def _patch_index(p: Path) -> None:
    s=p.read_text(encoding='utf-8')
    a=s.index('      <div class="auth-tabs">'); b=s.index('    </div>\n  </section>',a)
    auth='''      <form id="pinForm" class="stack simple-auth">\n        <label>名前（カタカナ）<input id="loginName" type="text" autocomplete="username" maxlength="20" placeholder="ケンイチロウ" required></label>\n        <label>6桁の暗証番号<input id="loginPin" type="password" inputmode="numeric" autocomplete="current-password" pattern="[0-9]{6}" minlength="6" maxlength="6" placeholder="••••••" required></label>\n        <button class="primary full">JJ Arenaへ入る</button>\n      </form>\n      <p id="authMessage" class="hint">初回はそのままアカウントを作成します。管理者の承認は不要です。</p>\n      <details class="privacy-note">\n        <summary>ログイン情報の取扱い</summary>\n        <p>メールアドレスは収集しません。名前と6桁PINだけを利用し、PINは復元できないハッシュとして保存します。ひらがなで入力した場合もカタカナへ自動統一されます。</p>\n      </details>\n'''
    s=s[:a]+auth+s[b:]
    s=s.replace('<button class="nav admin-only" data-view="members">♙ <span>メンバー管理</span></button>','<button class="nav admin-only" data-view="members">♙ <span>ユーザー管理</span></button>')
    old='<section id="membersView" class="view admin-only"><div class="section-head"><div><div class="eyebrow">ADMIN</div><h3>メンバー管理</h3></div></div><p class="notice">新規登録は承認制です。ランキング名は既存JJランキングの名前に合わせると、オンライン結果が同じ順位へ統合されます。</p><div id="memberList" class="member-grid"></div></section>'
    new='<section id="membersView" class="view admin-only"><div class="section-head"><div><div class="eyebrow">ADMIN</div><h3>ユーザー管理</h3></div></div><p class="notice">承認操作は不要です。必要な場合だけ利用停止、PINリセット、ランキング名の紐付けを行えます。</p><div id="memberList" class="member-grid"></div></section>'
    s=s.replace(old,new)
    p.write_text(s,encoding='utf-8')


def _patch_appjs(p: Path) -> None:
    s=p.read_text(encoding='utf-8')
    s=s.replace("members:['ADMIN','メンバー管理']","members:['ADMIN','ユーザー管理']")
    a=s.index('  async function renderMembers()'); b=s.index('\n\n  function makeQuiz()',a)
    render='''  async function renderMembers(){if(me.role!=='admin')return;const [members,ranks]=await Promise.all([api('/admin/members'),api('/rankings')]);const opts=ranks.map(r=>`<option value="${safe(r.name)}">${safe(r.name)}</option>`).join('');$('#memberList').innerHTML=members.map(m=>`<article class="card member-card"><div class="member-head"><div><strong>${safe(m.name)}</strong><div class="hint">${m.role==='admin'?'ADMIN':'MEMBER'} · Ranking: ${safe(m.ranking_name||m.name)}</div></div><span class="status-badge ${m.disabled?'danger-badge':'ok-badge'}">${m.disabled?'DISABLED':'ACTIVE'}</span></div><label>ランキング名<select data-ranking-name="${m.id}"><option value="${safe(m.ranking_name||m.name)}">${safe(m.ranking_name||m.name)}</option>${opts}</select></label><div class="button-row"><button class="soft" data-reset-pin="${m.id}">PINリセット</button>${m.role!=='admin'?`<button class="ghost" data-member-action="${m.disabled?'enable':'disable'}" data-member-id="${m.id}">${m.disabled?'利用再開':'利用停止'}</button>`:''}</div></article>`).join('')}'''
    s=s[:a]+render+s[b:]
    a=s.index('  function bind(){'); auth_end=s.index("    $('#logoutBtn')",a)
    prefix="  function bind(){\n    $('#pinForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await post('/auth/pin',{name:$('#loginName').value,pin:$('#loginPin').value});me=d.user;$('#loginPin').value='';showApp();await refreshAll();toast(d.created?'アカウントを作成しました':'ログインしました')}catch(err){toast(err.message)}});\n"
    s=s[:a]+prefix+s[auth_end:]
    s=s.replace("$('#accountBtn').addEventListener('click',()=>openModal(`<h3>アカウント設定</h3><p class=\"hint\">${safe(me.email)} · Ranking: ${safe(me.ranking_name||me.name)}</p><form id=\"passwordForm\" class=\"stack\"><label>現在のパスワード<input name=\"current_password\" type=\"password\" required></label><label>新しいパスワード<input name=\"new_password\" type=\"password\" minlength=\"8\" required></label><button class=\"primary\">パスワード変更</button></form>`));","$('#accountBtn').addEventListener('click',()=>openModal(`<h3>アカウント設定</h3><p class=\"hint\">${safe(me.name)} · Ranking: ${safe(me.ranking_name||me.name)}</p><form id=\"pinChangeForm\" class=\"stack\"><label>現在の6桁PIN<input name=\"current_pin\" type=\"password\" inputmode=\"numeric\" pattern=\"[0-9]{6}\" minlength=\"6\" maxlength=\"6\" required></label><label>新しい6桁PIN<input name=\"new_pin\" type=\"password\" inputmode=\"numeric\" pattern=\"[0-9]{6}\" minlength=\"6\" maxlength=\"6\" required></label><button class=\"primary\">PINを変更</button></form>`));")
    old="const ma=e.target.closest('[data-member-action]');if(ma){try{const id=Number(ma.dataset.memberId),act=ma.dataset.memberAction;await patch(`/admin/members/${id}`,act==='approve'?{approved:true}:act==='disable'?{disabled:true}:{disabled:false});toast('メンバー設定を更新しました');return renderMembers()}catch(err){return toast(err.message)}}const re=e.target.closest('[data-reveal-email]');if(re){try{const password=prompt('メールアドレス確認のため管理者パスワードを再入力してください');if(!password)return;const d=await post(`/admin/members/${re.dataset.revealEmail}/reveal-email`,{password});alert(`登録メール: ${d.email}`);return}catch(err){return toast(err.message)}}"
    new="const ma=e.target.closest('[data-member-action]');if(ma){try{const id=Number(ma.dataset.memberId),act=ma.dataset.memberAction;await patch(`/admin/members/${id}`,act==='disable'?{disabled:true}:{disabled:false});toast('ユーザー設定を更新しました');return renderMembers()}catch(err){return toast(err.message)}}const rp=e.target.closest('[data-reset-pin]');if(rp){const pin=prompt('新しい6桁PINを入力してください');if(!pin)return;if(!/^\\d{6}$/.test(pin))return toast('PINは6桁の数字で入力してください');try{await post(`/admin/members/${rp.dataset.resetPin}/reset-pin`,{pin});toast('PINをリセットしました');return}catch(err){return toast(err.message)}}"
    s=s.replace(old,new)
    s=s.replace("if(e.target.id==='passwordForm'){await post('/auth/change-password',Object.fromEntries(fd));closeModal();toast('パスワードを変更しました')}","if(e.target.id==='pinChangeForm'){await post('/auth/change-pin',Object.fromEntries(fd));closeModal();toast('PINを変更しました')}")
    p.write_text(s,encoding='utf-8')
