from __future__ import annotations
from pathlib import Path


def apply(root: Path) -> None:
    p=root/'server.py'; s=p.read_text(encoding='utf-8'); s=s.replace('version="1.11.0"','version="1.12.0"').replace('"version":"1.11.0"','"version":"1.12.0"').replace('request.url.query == "v=21"','request.url.query == "v=22"'); p.write_text(s,encoding='utf-8')
    p=root/'static'/'index.html'; s=p.read_text(encoding='utf-8').replace('?v=21','?v=22'); p.write_text(s,encoding='utf-8')
    p=root/'static'/'app.js'; s=p.read_text(encoding='utf-8'); s=s.replace("card.className='mobile-only mobile-quick-point card';","card.className='mobile-quick-point card';"); p.write_text(s,encoding='utf-8')
    p=root/'static'/'styles.css'; s=p.read_text(encoding='utf-8')
    if 'v1.12 desktop quick point' not in s:
        s += '''\n/* v1.12 desktop quick point — same operation is available from Home on every device */\n@media (min-width:761px){\n  .mobile-quick-point{display:block;margin:0 0 22px;padding:20px 22px;background:linear-gradient(145deg,#fff,#f8fbf9);border:1px solid rgba(17,115,78,.13);box-shadow:0 10px 30px rgba(20,86,59,.055)}\n  .mobile-section-title{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:15px}.mobile-section-title h3{margin:.15rem 0 0;font-size:1.35rem}.mobile-section-title>span{padding:5px 9px;border-radius:999px;background:#e7f6ef;color:#087a55;font-size:.62rem;font-weight:900;letter-spacing:.1em}\n  .quick-point-form{display:grid;grid-template-columns:1.35fr .8fr .9fr .7fr 1.2fr;gap:12px;align-items:end}.quick-point-form label{font-size:.7rem;font-weight:800;color:var(--muted,#65736c)}.quick-point-form input,.quick-point-form select{width:100%;margin-top:5px;min-height:44px;padding:9px 10px;border-radius:11px;background:#fff}\n  .quick-chip-block{grid-column:1/4;padding:12px;border:1px solid rgba(34,75,55,.09);border-radius:14px;background:#f7faf8}.quick-chip-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:9px;font-size:.75rem}.quick-chip-head span{font-size:.65rem;color:var(--muted,#65736c)}.quick-chip-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:7px}.quick-chip-grid label{padding:7px;border:1px solid rgba(34,75,55,.08);border-radius:10px;background:#fff;text-align:center}.quick-chip-grid label span{display:block;color:#263d32}.quick-chip-grid input{text-align:center;padding:6px 3px;min-height:38px;font-weight:850}\n  .quick-point-total{grid-column:4/6;display:flex;align-items:center;justify-content:space-between;align-self:stretch;padding:12px 15px;border-radius:14px;background:#143c30;color:#fff}.quick-point-total span{font-size:.75rem;opacity:.82}.quick-point-total>strong{font-size:1.25rem;font-variant-numeric:tabular-nums}.quick-submit{grid-column:4/6;min-height:46px;border-radius:12px;font-weight:900}\n  #homePointShortcut{display:none!important}\n}\n'''
    p.write_text(s,encoding='utf-8')
    p=root/'static'/'sw.js'; s=p.read_text(encoding='utf-8').replace('jj-arena-live-v11','jj-arena-live-v12'); p.write_text(s,encoding='utf-8')
