(()=>{
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const state={me:null,overview:null,users:[],ledger:[],audit:[],settings:null,direction:'credit',view:'dashboard'};
  const titles={dashboard:'管理概要',users:'登録アカウント',points:'ポイント振込・回収',settings:'ポイント制度設定',audit:'監査ログ'};
  const fmt=n=>new Intl.NumberFormat('ja-JP',{maximumFractionDigits:2}).format(Number(n||0));
  const safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const dt=v=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat('ja-JP',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)};
  const isoLocal=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
  let toastTimer;
  function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
  async function api(path,options={}){const opts={credentials:'include',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}};const res=await fetch('/api'+path,opts);let data=null;try{data=await res.json()}catch{}if(!res.ok){if(res.status===401){location.href='/';throw new Error('ログインが必要です')}throw new Error(data?.detail||`HTTP ${res.status}`)}return data}
  const post=(p,b)=>api(p,{method:'POST',body:JSON.stringify(b??{})}),patch=(p,b)=>api(p,{method:'PATCH',body:JSON.stringify(b??{})});
  function setView(view){if(!titles[view])return;state.view=view;$('#pageTitle').textContent=titles[view];$$('.view').forEach(v=>v.classList.toggle('active',v.id===view+'View'));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));history.replaceState(null,'','#'+view);if(view==='users')loadUsers();if(view==='points')loadLedger();if(view==='settings')loadSettings();if(view==='audit')loadAudit();window.scrollTo({top:0,behavior:'smooth'})}
  function actionLabel(a){return ({'user.update':'アカウント更新','user.sessions_revoke':'セッション失効','user.pin_reset':'PINリセット','point.credit':'ポイント振込','point.collection':'ポイント回収','point.reverse':'ポイント取消','settings.update':'制度設定変更'})[a]||a}
  async function loadOverview(){state.overview=await api('/admin/console/overview');const o=state.overview;$('#kpiAccounts').textContent=fmt(o.accounts.total);$('#kpiActive').textContent=`稼働 ${o.accounts.active} · 停止 ${o.accounts.disabled}`;$('#kpiVerified').textContent=fmt(o.accounts.verified);$('#kpiUnverified').textContent=`未確認 ${Math.max(0,o.accounts.total-o.accounts.verified)}`;$('#kpiCredit').textContent='+'+fmt(o.ledger.credited)+' pt';$('#kpiDebit').textContent='−'+fmt(o.ledger.collected)+' pt';const end=new Date(o.season.end_exclusive+'T00:00:00');end.setDate(end.getDate()-1);$('#seasonLabel').textContent=`${o.season.start.replaceAll('-','.')} — ${end.toISOString().slice(0,10).replaceAll('-','.')}`;const alerts=[],unverified=Math.max(0,o.accounts.total-o.accounts.verified);if(unverified)alerts.push(`<div class="alert-item"><strong>本人確認が未完了のアカウント ${unverified}件</strong><p>利用を止める必要はありません。登録名とJJメンバーの紐付けを確認できます。</p></div>`);if(o.duplicate_mappings?.length)o.duplicate_mappings.forEach(x=>alerts.push(`<div class="alert-item"><strong>ランキング名「${safe(x.ranking_name)}」が ${x.n} アカウントに紐付いています</strong><p>意図した共有でなければアカウント管理から修正してください。</p></div>`));$('#alerts').innerHTML=alerts.join('')||'<div class="empty-state">現在、重大な確認事項はありません。</div>';$('#recentAudit').innerHTML=(o.recent_audit||[]).map(a=>`<div class="timeline-item"><i class="timeline-dot"></i><div><strong>${safe(actionLabel(a.action))}${a.target_name?` · ${safe(a.target_name)}`:''}</strong><small>${safe(a.actor_name||'—')} · ${dt(a.created_at)}</small></div></div>`).join('')||'<div class="empty-state">まだ管理操作はありません。</div>'}
  async function loadUsers(){const q=$('#userSearch').value.trim(),show=$('#showDisabled').checked;state.users=await api(`/admin/console/users?q=${encodeURIComponent(q)}&include_disabled=${show?'true':'false'}`);renderUsers();fillPointUsers()}
  function statusHtml(u){return `<span class="badge ${u.disabled?'disabled':'active'}">${u.disabled?'利用停止':'ACTIVE'}</span>${u.club_verified?'<span class="badge verify">確認済</span>':'<span class="badge warn">未確認</span>'}${u.duplicate_mapping?'<span class="badge warn">重複</span>':''}`}
  function renderUsers(){const rows=state.users.map(u=>`<tr><td class="account-name"><strong>${safe(u.name)}</strong><small>ID ${u.id} · ${safe(u.role.toUpperCase())}</small></td><td>${statusHtml(u)}</td><td><strong>${safe(u.ranking_name||u.name)}</strong></td><td class="points-cell ${u.season_points>=0?'positive':'negative'}">${u.season_points>=0?'+':''}${fmt(u.season_points)}</td><td>${Number(u.active_sessions||0)}<br><small>${dt(u.last_login_at)}</small></td><td><button class="row-btn" data-user-edit="${u.id}">管理</button></td></tr>`).join('');$('#usersBody').innerHTML=rows||'<tr><td colspan="6" class="empty-state">該当するアカウントがありません。</td></tr>';$('#usersCards').innerHTML=state.users.map(u=>`<article class="user-card"><div class="user-card-head"><div><strong>${safe(u.name)}</strong><small>ID ${u.id} · ${safe(u.ranking_name||u.name)}</small></div><div>${statusHtml(u)}</div></div><div class="user-card-metrics"><div><span>後期Pt</span><b>${u.season_points>=0?'+':''}${fmt(u.season_points)}</b></div><div><span>Online</span><b>${u.online_points>=0?'+':''}${fmt(u.online_points)}</b></div><div><span>Session</span><b>${u.active_sessions||0}</b></div></div><button class="row-btn" data-user-edit="${u.id}">管理する</button></article>`).join('')}
  function openUser(id){const u=state.users.find(x=>Number(x.id)===Number(id));if(!u)return;const admin=u.role==='admin';$('#userDialogBody').innerHTML=`<div class="dialog-inner"><div class="eyebrow">ACCOUNT #${u.id}</div><h3>${safe(u.name)}</h3><div class="dialog-meta">${safe(u.role.toUpperCase())} · 作成 ${dt(u.created_at)}</div><div class="detail-kpis"><div><span>後期合計</span><b>${u.season_points>=0?'+':''}${fmt(u.season_points)} pt</b></div><div><span>Club / Online</span><b>${fmt(u.club_points)} / ${fmt(u.online_points)}</b></div><div><span>管理調整</span><b>${u.admin_points>=0?'+':''}${fmt(u.admin_points)}</b></div></div><form id="userEditForm" class="form-stack" data-user-id="${u.id}"><label>ランキング紐付け名<input name="ranking_name" maxlength="60" value="${safe(u.ranking_name||u.name)}" required></label><label class="check"><input name="club_verified" type="checkbox" ${u.club_verified?'checked':''}> JJメンバーとして確認済みにする</label><label>管理メモ<textarea name="admin_note" maxlength="1000" rows="3" placeholder="運営だけに表示">${safe(u.admin_note||'')}</textarea></label><button class="primary">アカウント情報を保存</button></form><div class="dialog-actions">${!admin?`<button class="${u.disabled?'ok-btn':'danger-btn'}" data-toggle-disabled="${u.id}" data-next="${u.disabled?'0':'1'}">${u.disabled?'利用を再開':'利用を停止'}</button><button class="soft" data-reset-pin="${u.id}">PINリセット</button><button class="soft" data-revoke="${u.id}">全セッション失効</button>`:'<span class="field-note">管理者アカウントの停止・PINリセットはこの画面では行いません。</span>'}</div></div>`;$('#userDialog').showModal()}
  function fillPointUsers(){const sel=$('#pointUser');if(!sel)return;const cur=sel.value,users=state.users.filter(u=>!u.disabled).sort((a,b)=>a.name.localeCompare(b.name,'ja'));sel.innerHTML='<option value="">選択してください</option>'+users.map(u=>`<option value="${u.id}">${safe(u.name)} · ${safe(u.ranking_name||u.name)} · ${u.season_points>=0?'+':''}${fmt(u.season_points)}pt</option>`).join('');if(users.some(u=>String(u.id)===cur))sel.value=cur}
  async function loadLedger(){if(!state.users.length)await loadUsers();state.ledger=await api('/admin/console/points?limit=250');renderLedger()}
  function renderLedger(){$('#ledgerList').innerHTML=state.ledger.map(x=>{const positive=Number(x.amount)>=0,undoable=!x.reversal_of&&!x.reversed;return `<div class="ledger-item ${x.reversed?'reversed':''}"><div><strong>${safe(x.user_name)} · ${safe(x.ranking_name)}</strong><p>${safe(x.reason)}<br>${safe(x.actor_name||'—')} · 反映 ${dt(x.effective_at)} · 記録 ${dt(x.created_at)}</p>${x.reversal_of?`<p>取消元: ${safe(x.reversal_of.slice(0,12))}…</p>`:''}</div><div class="ledger-amount"><b class="${positive?'credit':'debit'}">${positive?'+':''}${fmt(x.amount)} pt</b><small>${x.kind==='credit'?'振込':x.kind==='collection'?'回収':x.kind==='reversal'?'取消':safe(x.kind)}</small>${undoable?`<button class="reverse-btn" data-reverse="${safe(x.id)}">取消</button>`:x.reversed?'<small>取消済</small>':''}</div></div>`}).join('')||'<div class="empty-state">管理者によるポイント操作はまだありません。</div>'}
  async function loadSettings(){state.settings=await api('/admin/console/settings');$('#settingRate').value=state.settings.online_points_per_bb;$('#settingLimit').value=state.settings.manual_adjustment_limit;const end=new Date(state.settings.season_end_exclusive+'T00:00:00');end.setDate(end.getDate()-1);$('#policySeason').textContent=`${state.settings.season_start} 〜 ${end.toISOString().slice(0,10)}`}
  async function loadAudit(){state.audit=await api('/admin/console/audit?limit=250');$('#auditList').innerHTML=state.audit.map(a=>{let detail='';try{const d=JSON.parse(a.detail_json||'{}');if(d.amount!==undefined)detail+=`${Number(d.amount)>=0?'+':''}${fmt(d.amount)}pt `;if(d.reason)detail+=d.reason;if(d.changed)detail+=Object.entries(d.changed).map(([k,v])=>`${k}=${v}`).join(' / ')}catch{}return `<div class="audit-row"><time>${dt(a.created_at)}</time><div class="audit-action">${safe(actionLabel(a.action))}<br><small>${safe(a.actor_name||'—')}${a.target_name?` → ${safe(a.target_name)}`:''}</small></div><div class="audit-detail">${safe(detail||'—')}</div></div>`}).join('')||'<div class="empty-state">監査ログはまだありません。</div>'}
  function updatePointPreview(){const amount=Math.max(0,Number($('#pointAmount').value||0)),credit=state.direction==='credit';$('#pointPreview').textContent=(credit?'+':'−')+fmt(amount)+' pt';$('#pointPreview').classList.toggle('debit',!credit)}
  function downloadCsv(name,rows){if(!rows.length)return toast('出力するデータがありません');const keys=Object.keys(rows[0]),esc=v=>`"${String(v??'').replaceAll('"','""')}"`,csv='\ufeff'+[keys.map(esc).join(','),...rows.map(r=>keys.map(k=>esc(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])).join(','))].join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function bind(){
    $$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.jump)));
    let searchTimer;$('#userSearch').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadUsers,220)});$('#showDisabled').addEventListener('change',loadUsers);$('#refreshUsers').addEventListener('click',loadUsers);
    document.addEventListener('click',async e=>{const edit=e.target.closest('[data-user-edit]');if(edit)return openUser(edit.dataset.userEdit);const toggle=e.target.closest('[data-toggle-disabled]');if(toggle){const id=Number(toggle.dataset.toggleDisabled),disabled=toggle.dataset.next==='1';if(disabled&&!confirm('このアカウントを利用停止にします。既存セッションも失効します。'))return;try{await patch(`/admin/console/users/${id}`,{disabled});toast(disabled?'利用停止にしました':'利用を再開しました');$('#userDialog').close();await loadUsers();await loadOverview()}catch(err){toast(err.message)}return}const reset=e.target.closest('[data-reset-pin]');if(reset){const pin=prompt('新しい6桁PINを入力してください');if(!pin)return;if(!/^\d{6}$/.test(pin))return toast('PINは6桁の数字です');if(!confirm('PINをリセットすると、そのユーザーの既存セッションは失効します。続行しますか？'))return;try{await post(`/admin/console/users/${reset.dataset.resetPin}/reset-pin`,{pin});toast('PINをリセットしました');$('#userDialog').close();await loadUsers()}catch(err){toast(err.message)}return}const revoke=e.target.closest('[data-revoke]');if(revoke){if(!confirm('このユーザーを全端末からログアウトさせますか？'))return;try{await post(`/admin/console/users/${revoke.dataset.revoke}/revoke-sessions`,{});toast('全セッションを失効しました');$('#userDialog').close();await loadUsers()}catch(err){toast(err.message)}return}const rev=e.target.closest('[data-reverse]');if(rev){if(!confirm('このポイント取引を取消しますか？ 元データは削除せず、反対取引を追加します。'))return;try{await post(`/admin/console/points/${rev.dataset.reverse}/reverse`,{});toast('取消取引を記録しました');await Promise.all([loadLedger(),loadUsers(),loadOverview()])}catch(err){toast(err.message)}}});
    $('#closeUserDialog').addEventListener('click',()=>$('#userDialog').close());$('#userDialog').addEventListener('click',e=>{if(e.target===$('#userDialog'))$('#userDialog').close()});$('#userDialog').addEventListener('submit',async e=>{if(e.target.id!=='userEditForm')return;e.preventDefault();const fd=new FormData(e.target),id=Number(e.target.dataset.userId);try{await patch(`/admin/console/users/${id}`,{ranking_name:String(fd.get('ranking_name')||'').trim(),club_verified:fd.get('club_verified')==='on',admin_note:String(fd.get('admin_note')||'')});toast('アカウント情報を保存しました');$('#userDialog').close();await Promise.all([loadUsers(),loadOverview()])}catch(err){toast(err.message)}});
    $$('.direction button').forEach(b=>b.addEventListener('click',()=>{state.direction=b.dataset.direction;$$('.direction button').forEach(x=>x.classList.toggle('active',x===b));updatePointPreview()}));$('#pointAmount').addEventListener('input',updatePointPreview);$('#pointEffective').value=isoLocal();$('#pointForm').addEventListener('submit',async e=>{e.preventDefault();const uid=Number($('#pointUser').value),amount=Number($('#pointAmount').value),reason=$('#pointReason').value.trim(),effective=$('#pointEffective').value;if(!uid)return toast('対象アカウントを選択してください');const verb=state.direction==='credit'?'振込':'回収',target=state.users.find(u=>u.id===uid);if(!confirm(`${target?.name||'対象'} に ${fmt(amount)}pt を${verb}します。よろしいですか？`))return;try{await post('/admin/console/points',{user_id:uid,direction:state.direction,amount,reason,effective_at:effective});toast(`ポイントを${verb}しました`);$('#pointAmount').value='';$('#pointReason').value='';$('#pointEffective').value=isoLocal();updatePointPreview();await Promise.all([loadLedger(),loadUsers(),loadOverview()])}catch(err){toast(err.message)}});
    $('#refreshLedger').addEventListener('click',loadLedger);$('#exportLedger').addEventListener('click',()=>downloadCsv(`jj-point-ledger-${new Date().toISOString().slice(0,10)}.csv`,state.ledger));$('#exportUsers').addEventListener('click',()=>downloadCsv(`jj-accounts-${new Date().toISOString().slice(0,10)}.csv`,state.users));$('#settingsForm').addEventListener('submit',async e=>{e.preventDefault();const body={online_points_per_bb:Number($('#settingRate').value),manual_adjustment_limit:Number($('#settingLimit').value)};if(!confirm(`オンライン換算を 1bb=${body.online_points_per_bb}pt に設定します。過去結果は変更しません。続行しますか？`))return;try{state.settings=await patch('/admin/console/settings',body);toast('制度設定を保存しました');await Promise.all([loadSettings(),loadOverview()])}catch(err){toast(err.message)}});$('#refreshAudit').addEventListener('click',loadAudit)
  }
  async function init(){try{state.me=await api('/me');if(state.me.role!=='admin')throw new Error('管理者権限が必要です');$('#adminName').textContent=state.me.name;bind();const hash=location.hash.replace('#','');setView(titles[hash]?hash:'dashboard');await Promise.all([loadOverview(),loadUsers(),loadSettings()]);if(state.view==='points')await loadLedger();if(state.view==='audit')await loadAudit();updatePointPreview()}catch(err){document.body.innerHTML=`<main style="max-width:560px;margin:12vh auto;padding:24px;font-family:system-ui"><h1>Admin Console</h1><p>${safe(err.message)}</p><p><a href="/">JJ Arenaへ戻る</a></p></main>`}}
  init();
})();
